site_name: RingCentral Engage Developer Docs
site_url: https://engage-api-docs.rtfd.org
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/engage-api-docs
docs_dir: docs
theme:
  name: moonstone
  custom_dir: 'theme/'
  fluid_layout: False
  suppress_nextprev: true
  shortcuts:
    - foo

#extra_css: [extra.css]
#extra_javascript: [fonts.js]
pages:
- 'Overview': index.md
- 'Digital - Webhooks': digital_webhook.md
- 'Digital - Chatbots': digital_chatbot.md